"""Added user feedback and user feed weights

Revision ID: 0e665f20559a
Revises: f3cfa5ef8374
Create Date: 2024-03-31 15:21:59.838535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e665f20559a'
down_revision = 'f3cfa5ef8374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserFeedWeights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('personality', sa.Integer(), nullable=True),
    sa.Column('mentor_gender_preference', sa.Integer(), nullable=True),
    sa.Column('interests', sa.Integer(), nullable=True),
    sa.Column('career_interests', sa.Integer(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('UserFeedWeights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserFeedWeights_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('Business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_solicitation_frequency', sa.Integer(), nullable=True))

    with op.batch_alter_table('UserFeedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFeedback', schema=None) as batch_op:
        batch_op.drop_column('meeting_number')

    with op.batch_alter_table('Business', schema=None) as batch_op:
        batch_op.drop_column('feedback_solicitation_frequency')

    with op.batch_alter_table('UserFeedWeights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserFeedWeights_user_id'))

    op.drop_table('UserFeedWeights')
    # ### end Alembic commands ###
