"""added progress meetings

Revision ID: 112dcfa42b0b
Revises: f9ef20b238a0
Create Date: 2022-03-01 18:41:53.559853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112dcfa42b0b'
down_revision = 'f9ef20b238a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProgressMeeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_ID', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('num_meeting', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content_description', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ProgressMeeting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ProgressMeeting_completion_date'), ['completion_date'], unique=False)

    with op.batch_alter_table('Select', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_meeting_ID', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Select', schema=None) as batch_op:
        batch_op.drop_column('current_meeting_ID')

    with op.batch_alter_table('ProgressMeeting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ProgressMeeting_completion_date'))

    op.drop_table('ProgressMeeting')
    # ### end Alembic commands ###
