"""generalized name of meeting notes, added timestamp

Revision ID: 36c38d28de90
Revises: 4d81559ad6d1
Create Date: 2022-05-20 21:35:08.188399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c38d28de90'
down_revision = '4d81559ad6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("MeetingNotes", "ProgressMeetingCompletionInformation")

    with op.batch_alter_table('ProgressMeetingCompletionInformation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_timestamp_mentor', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completion_timestamp_mentee', sa.DateTime(), nullable=True))

    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('ProgressMeetingCompletionInformation', schema=None) as batch_op:
        batch_op.drop_column('completion_timestamp_mentor')
        batch_op.drop_column('completion_timestamp_mentee')


    op.rename_table("ProgressMeetingCompletionInformation", "MeetingNotes")
        
    # ### end Alembic commands ###
