"""added column for actual name added

Revision ID: 38aaeb5a6458
Revises: cda4c20cf2cd
Create Date: 2021-02-27 12:24:05.420811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aaeb5a6458'
down_revision = 'cda4c20cf2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CareerInterestTag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_name', sa.String(length=64), nullable=True))

    with op.batch_alter_table('EducationTag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_name', sa.String(length=64), nullable=True))

    with op.batch_alter_table('InterestTag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered_name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('InterestTag', schema=None) as batch_op:
        batch_op.drop_column('entered_name')

    with op.batch_alter_table('EducationTag', schema=None) as batch_op:
        batch_op.drop_column('entered_name')

    with op.batch_alter_table('CareerInterestTag', schema=None) as batch_op:
        batch_op.drop_column('entered_name')

    # ### end Alembic commands ###
