"""added resume

Revision ID: 420c7f884bef
Revises: b585c8a204bc
Create Date: 2022-01-13 00:32:22.587270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420c7f884bef'
down_revision = 'b585c8a204bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resume_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('resume_key')
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
