"""moved meeting notes to own class

Revision ID: 4d81559ad6d1
Revises: d824814ed495
Create Date: 2022-05-19 22:19:40.499358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d81559ad6d1'
down_revision = 'd824814ed495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MeetingNotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_progress_meeting', sa.Integer(), nullable=True),
    sa.Column('select_id', sa.Integer(), nullable=True),
    sa.Column('mentor_meeting_notes', sa.Text(), nullable=True),
    sa.Column('mentee_meeting_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Select', schema=None) as batch_op:
        batch_op.drop_column('mentor_meeting_notes')
        batch_op.drop_column('mentee_meeting_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Select', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentee_meeting_notes', mysql.VARCHAR(length=10000), nullable=True))
        batch_op.add_column(sa.Column('mentor_meeting_notes', mysql.TEXT(), nullable=True))

    op.drop_table('MeetingNotes')
    # ### end Alembic commands ###
