"""added profile picture

Revision ID: 5518f0a289c4
Revises: 96a6aaebccaa
Create Date: 2021-03-07 00:27:43.994215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5518f0a289c4'
down_revision = '96a6aaebccaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
