"""added profile picture key

Revision ID: 5789b35911aa
Revises: dbcdb866685b
Create Date: 2021-03-10 13:42:42.211078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5789b35911aa'
down_revision = 'dbcdb866685b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_key')

    # ### end Alembic commands ###
