"""Default value for feedback frequency = 0

Revision ID: 5b55291ba0f5
Revises: ff729f2fcbaa
Create Date: 2024-04-18 21:46:02.766896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b55291ba0f5'
down_revision = 'ff729f2fcbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProgressMeetingCompletionInformation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentee'), ['completion_timestamp_mentee'], unique=False)
        batch_op.create_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentor'), ['completion_timestamp_mentor'], unique=False)
        batch_op.drop_index('ix_ProgressMeetingCompletionInformation_completion_times_1b66')
        batch_op.drop_index('ix_ProgressMeetingCompletionInformation_completion_times_21d8')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProgressMeetingCompletionInformation', schema=None) as batch_op:
        batch_op.create_index('ix_ProgressMeetingCompletionInformation_completion_times_21d8', ['completion_timestamp_mentor'], unique=False)
        batch_op.create_index('ix_ProgressMeetingCompletionInformation_completion_times_1b66', ['completion_timestamp_mentee'], unique=False)
        batch_op.drop_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentor'))
        batch_op.drop_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentee'))

    # ### end Alembic commands ###
