"""Default value for feedback frequency = 0

Revision ID: 5b55291ba0f5
Revises: ff729f2fcbaa
Create Date: 2024-04-18 21:46:02.766896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b55291ba0f5'
down_revision = 'ff729f2fcbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Business', schema=None) as batch_op:
        op.alter_column('Business', 'feedback_solicitation_frequency',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default='0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Business', schema=None) as batch_op:
        op.alter_column('Business', 'feedback_solicitation_frequency',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default=None)
    # ### end Alembic commands ###
