"""added usage stat to tags

Revision ID: 69a1aeedc993
Revises: 837e56d1c349
Create Date: 2021-03-03 14:18:45.276541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a1aeedc993'
down_revision = '837e56d1c349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CareerInterest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_use', sa.Integer(), nullable=True))

    with op.batch_alter_table('School', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_use', sa.Integer(), nullable=True))

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_use', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.drop_column('num_use')

    with op.batch_alter_table('School', schema=None) as batch_op:
        batch_op.drop_column('num_use')

    with op.batch_alter_table('CareerInterest', schema=None) as batch_op:
        batch_op.drop_column('num_use')

    # ### end Alembic commands ###
