"""remigration with business because the previous database had head merging issues

Revision ID: 6f0efddfc806
Revises: ceebf57c599e
Create Date: 2021-12-20 14:57:21.739937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0efddfc806'
down_revision = 'ceebf57c599e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('number_employees_maximum', sa.Integer(), nullable=True),
    sa.Column('number_employees_currently_registered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('business_id')

    op.drop_table('Business')
    # ### end Alembic commands ###
