"""Added user feedback table

Revision ID: 7241c786546a
Revises: ceaec6334293
Create Date: 2024-01-21 17:52:55.917077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7241c786546a'
down_revision = 'ceaec6334293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserFeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('UserFeedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UserFeedback_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_UserFeedback_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFeedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UserFeedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_UserFeedback_timestamp'))

    op.drop_table('UserFeedback')
    # ### end Alembic commands ###
