"""changed swipe base to student and target to mentor for clarity.

Revision ID: 96a6aaebccaa
Revises: fe2715e163be
Create Date: 2021-03-06 18:30:01.262379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a6aaebccaa'
down_revision = 'fe2715e163be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Swipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.drop_column('base_user_id')
        batch_op.drop_column('target_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Swipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('base_user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('student_id')
        batch_op.drop_column('mentor_id')

    # ### end Alembic commands ###
