"""Changed swipe to select

Revision ID: 9b9fbab1f375
Revises: e04de323399d
Create Date: 2021-11-26 00:52:08.001791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b9fbab1f375'
down_revision = 'e04de323399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('mentee_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Select', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Select_timestamp'), ['timestamp'], unique=False)

    op.drop_table('Swipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Swipe',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('match', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('shown', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`likes` in (0,1))', name='Swipe_chk_1'),
    sa.CheckConstraint('(`match` in (0,1))', name='Swipe_chk_2'),
    sa.CheckConstraint('(`shown` in (0,1))', name='Swipe_chk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Select', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Select_timestamp'))

    op.drop_table('Select')
    # ### end Alembic commands ###
