"""added videos

Revision ID: 9cf31f98a582
Revises: d4da63425a12
Create Date: 2021-04-20 23:55:59.310265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cf31f98a582'
down_revision = 'd4da63425a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CareerInterest', schema=None) as batch_op:
        batch_op.drop_constraint('CareerInterest_ibfk_1', type_='foreignkey')
        batch_op.drop_column('careerInterestID')

    with op.batch_alter_table('School', schema=None) as batch_op:
        batch_op.drop_constraint('School_ibfk_1', type_='foreignkey')
        batch_op.drop_column('schoolID')

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.drop_constraint('Tag_ibfk_1', type_='foreignkey')
        batch_op.drop_column('tagID')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro_video', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intro_video_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('intro_video_key')
        batch_op.drop_column('intro_video')

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Tag_ibfk_1', 'InterestTag', ['tagID'], ['id'])

    with op.batch_alter_table('School', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schoolID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('School_ibfk_1', 'EducationTag', ['schoolID'], ['id'])

    with op.batch_alter_table('CareerInterest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('careerInterestID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('CareerInterest_ibfk_1', 'CareerInterestTag', ['careerInterestID'], ['id'])

    # ### end Alembic commands ###
