"""added option for multiple pairings to User

Revision ID: c108a9045fc6
Revises: 36c38d28de90
Create Date: 2022-10-27 16:55:02.882503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c108a9045fc6'
down_revision = '36c38d28de90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProgressMeetingCompletionInformation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentee'), ['completion_timestamp_mentee'], unique=False)
        batch_op.create_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentor'), ['completion_timestamp_mentor'], unique=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pairings_can_make', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('num_pairings_can_make')

    with op.batch_alter_table('ProgressMeetingCompletionInformation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentor'))
        batch_op.drop_index(batch_op.f('ix_ProgressMeetingCompletionInformation_completion_timestamp_mentee'))

    # ### end Alembic commands ###
