"""change is student

Revision ID: cda4c20cf2cd
Revises: a4d710ab784b
Create Date: 2021-02-17 15:22:49.777475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda4c20cf2cd'
down_revision = 'a4d710ab784b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_student', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_teacher', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_student')

    # ### end Alembic commands ###
