"""Added Admin user table

Revision ID: ceaec6334293
Revises: c108a9045fc6
Create Date: 2023-11-09 09:37:20.109135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaec6334293'
down_revision = 'c108a9045fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdminUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AdminUser', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AdminUser_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AdminUser', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AdminUser_email'))

    op.drop_table('AdminUser')
    # ### end Alembic commands ###
