"""added phone number

Revision ID: d4da63425a12
Revises: 5789b35911aa
Create Date: 2021-04-02 22:56:03.896339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4da63425a12'
down_revision = '5789b35911aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_contact', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email_contact')

    # ### end Alembic commands ###
