"""changed base and target back to preserve position changes

Revision ID: dbcdb866685b
Revises: 5518f0a289c4
Create Date: 2021-03-07 11:10:06.832973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcdb866685b'
down_revision = '5518f0a289c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Swipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.drop_column('student_id')
        batch_op.drop_column('mentor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Swipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('target_id')
        batch_op.drop_column('base_id')

    # ### end Alembic commands ###
