"""Added business id column to user feedback table

Revision ID: f3cfa5ef8374
Revises: 7241c786546a
Create Date: 2024-01-31 12:50:36.144931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cfa5ef8374'
down_revision = '7241c786546a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFeedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserFeedback', schema=None) as batch_op:
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
