"""added events, also changed feed to store match info

Revision ID: f9ef20b238a0
Revises: ff13e9fa4189
Create Date: 2022-02-19 20:41:28.427422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ef20b238a0'
down_revision = 'ff13e9fa4189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Event_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Event_timestamp'))

    op.drop_table('Event')
    # ### end Alembic commands ###
