"""added Swipe table

Revision ID: fe2715e163be
Revises: 69a1aeedc993
Create Date: 2021-03-06 13:06:51.353842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2715e163be'
down_revision = '69a1aeedc993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Swipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Boolean(), nullable=True),
    sa.Column('match', sa.Boolean(), nullable=True),
    sa.Column('shown', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Swipe')
    # ### end Alembic commands ###
